### PR TITLE
add base predictor option to regression and easy modules #89

### LINKED ISSUE #89: Base Predictors
Allow users to specify a base predictor that predicts population, cluster, or cohort models, so that contextualized models only learn context-specific effects not represented in the base predictor.
 
Base predictor interface for `regression` and `easy`:
```
BasePredictor:
  predict_params(self, C): returns a numpy array of parameters matching the output shape of _params_reshape
```
Base predictions and context-specific predictions should be summed in `ContextualizedRegressionBase.forward`

Resolve #87 before addressing this issue for `dags`

### PR DESCRIPTION
**Pull request by cnellington**
Added a base predictor kwarg to ContextualizedRegressionBase and enabled for all `regression` and `easy` classes.
Added base predictor kwarg quicktests to `regression` and `easy`
Resolves #89 for `regression` and `easy`

### CODE REVIEW

**Review by blengerich — CHANGES_REQUESTED** [review]
To me, Base Predictor should predict the outcomes, not the parameters (because they may be other model classes, ie nonparametric, which can't be combined with the sample-specific coefficients). If we want a BaseCoefficientPredictor for parameters, it might be good to separate this function from the BasePredictor.

**Comment by cnellington** [comment]
Added the base_y_predictor and base_param_predictor kwargs for contextualized linear models. Adding a base_y_predictor makes the contextualized module predict only non-base effects, while adding a base_param_predictor will include the base effects in the contextualized parameter estimates. Or similarly, adding a base_param_predictor may help with learning heterogeneous effects but still includes homogeneous (base) effects in predictions, while adding a base_y_predictor will only learn/predict heterogeneous (non-base) effects.

These kwargs should be mutually exclusive in practice, but they're both used in the tests since the dummy classes are only there to help check tensor shapes and make sure we don't break torch autograd.

**Review by blengerich — APPROVED** [review]
LGTM!

At some point, we may want to add logging "warning" if unintended functionality is used (e.g. both base_y_predictor and base_param_predictor are given).

**Comment by cnellington** [comment]
Agreed, I think this type of warning extends to many of our kwargs so I'll make an issue to sanity-check arguments in all contextualized models.

**Pull request merged**
